[tool.poetry]
name = "pymortar"
version = "2.0.0a7"
description = ""
authors = ["Gabe Fierro <gtfierro@cs.berkeley.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
rdflib = "^5.0.0"
requests = "^2.25.0"
pyarrow = "^2.0.0"
pandas = "^1.1.5"
googleapis-common-protos = "^1.52.0"
brickschema = "0.3.0a4"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
